# Generated by Django 2.1.7 on 2019-04-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationWebhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_uuid', models.CharField(max_length=36)),
                ('source', models.CharField(max_length=65)),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
