# Generated by Django 2.1.7 on 2019-04-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinationWebhook', '0003_webhooktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooktransaction',
            name='body',
            field=models.TextField(),
        ),
    ]
